packages:
    - "apps/*"
    - "packages/*"

# Define a catalog of version ranges.
catalog:
    react: ^19.1.0
    react-dom: ^19.1.0
    react-tracked: 2.0.1
    lucide-react: 0.503.0
    react-dnd: 16.0.1
    react-dnd-html5-backend: 16.0.1
    react-hook-form: 7.62.0
    react-hotkeys-hook: 5.0.1

    ahooks: 3.8.4
    axios: 1.9.0
    classnames: 2.5.1
    zustand: 5.0.3
    immer: 10.1.1
    clsx: 2.1.1
    dayjs: 1.11.13
    nanoid: 5.1.5
    radash: 12.1.0
    lodash-es: 4.17.21
    dexie: 4.0.11
    lowdb: 7.0.1
    overlayscrollbars: 2.11.3
    overlayscrollbars-react: 0.5.5
    spark-md5: 3.0.2
    katex: 0.16.22
    js-cookie: 3.0.5
    colorthief: 2.6.0
    clipboard: 2.0.11
    i18next: 25.0.1
    i18next-browser-languagedetector: 8.0.5
    react-i18next: 15.4.1
    zod: 4.0.14

    eventemitter3: 5.0.1
    framer-motion: 12.23.5

    "@heroicons/react": 2.2.0

    "@tanstack/react-router": 1.130.12
    "@tanstack/react-router-devtools": 1.130.12

    "@legendapp/state": 3.0.0-beta.31
    "@dnd-kit/react": 0.1.2

    "@hookform/resolvers": 5.2.1

    "@tauri-apps/api": "2.5.0"
    "@tauri-apps/plugin-fs": "2.2.1"
    "@tauri-apps/plugin-store": "2.2.0"
    "@tauri-apps/plugin-shell": "2.2.1"
    "@tauri-apps/plugin-dialog": "2.2.1"
    "@tauri-apps/plugin-sql": "2.2.0"
    "@tauri-apps/cli": 2.5.0

    "inversify": 7.6.1
    reflect-metadata: 0.2.2
    "@abraham/reflection": 0.13.0

    "@tiptap/core": "3.0.7"
    "@tiptap/extension-document": "3.0.7"
    "@tiptap/extension-history": "3.0.7"
    "@tiptap/extension-paragraph": "3.0.7"
    "@tiptap/extension-placeholder": "3.0.7"
    "@tiptap/extension-task-item": "3.0.7"
    "@tiptap/extension-task-list": "3.0.7"
    "@tiptap/extension-text": "3.0.7"
    "@tiptap/starter-kit": "3.0.7"

    "@rsbuild/core": 1.4.13
    "@rsbuild/plugin-react": 1.3.4
    "@rsbuild/plugin-sass": 1.3.3

    vite: 7.0.3
    vitest: 3.2.4
    vitepress: 1.6.3
    "@vitejs/plugin-react": 4.6.0

    tailwindcss: 4.1.10
    tailwind-merge: 3.3.0
    "@tailwindcss/vite": 4.1.10
    "@tailwindcss/postcss": 4.1.10

    tsup: 8.4.0
    turbo: 2.5.5
    "@turbo/gen": 2.5.5

    shadcn: 2.9.3

    typescript: 5.1.6
    internal-ip: ^7.0.0

    "@biomejs/biome": 2.1.2
    "rollup-plugin-visualizer": "6.0.1"

    "@changesets/cli": 2.29.2

    "@testing-library/jest-dom": 6.6.3
    "@testing-library/react": 16.2.0

    "@types/react": ^19.1.2
    "@types/react-dom": ^19.1.1
    "@types/node": ^18.15.11
    "@types/lodash-es": 4.17.12
    "@types/overlayscrollbars": 1.12.5
    "@types/spark-md5": 3.0.5
    "@types/js-cookie": 3.0.6
    "@types/clipboard": 2.0.10
    "@types/katex": 0.16.7
